# Generated by Django 2.2.5 on 2019-09-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190909_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram1', to='attendance.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='attendance.Team')),
            ],
        ),
    ]
