# Generated by Django 2.2.5 on 2019-09-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='attendance.Team'),
        ),
    ]
