# Generated by Django 2.2.5 on 2019-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190912_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_table_release',
            field=models.BooleanField(default=False, verbose_name='マッチング表の公表'),
        ),
        migrations.AddField(
            model_name='match',
            name='register_release',
            field=models.BooleanField(default=False, verbose_name='登録ページの公表'),
        ),
    ]
