# Generated by Django 2.2.5 on 2019-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20190913_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_point',
            new_name='team_lose',
        ),
        migrations.AddField(
            model_name='player',
            name='b_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='b_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='d_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='d_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='e_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='e_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='nc_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='nc_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='nm_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='nm_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='r_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='r_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='v_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='v_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='w_lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='w_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='team',
            name='team_win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
