# Generated by Django 2.2.5 on 2019-09-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20190915_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_lose',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_win',
        ),
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('point', models.CharField(default='', max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(default='', max_length=100)),
                ('wl', models.CharField(default='', max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Player')),
            ],
        ),
    ]
