# Generated by Django 2.2.5 on 2019-09-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20190915_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='grosspoint',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
