# Generated by Django 2.2.5 on 2019-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20190916_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='point',
            new_name='lose',
        ),
        migrations.AddField(
            model_name='player',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
