# Generated by Django 2.2.5 on 2019-09-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20190916_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWinRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nm', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('d', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('b', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('r', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('v', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('w', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nc', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
            ],
        ),
    ]
