# Generated by Django 2.2.5 on 2019-09-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_deckcode_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcode',
            name='match',
        ),
    ]
